// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC84QvFvRGBHDuuJntJEwuU6vOjLdtbaYA',
    appId: '1:510267432954:web:2e86bec3d2689ca5afce43',
    messagingSenderId: '510267432954',
    projectId: 'chatapp-e0d07',
    authDomain: 'chatapp-e0d07.firebaseapp.com',
    storageBucket: 'chatapp-e0d07.appspot.com',
    measurementId: 'G-2F99H4ESTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_jtfW00bLEqKnfed2wOBY1omSOska1ZI',
    appId: '1:510267432954:android:fbdfa20a19bcbc8dafce43',
    messagingSenderId: '510267432954',
    projectId: 'chatapp-e0d07',
    storageBucket: 'chatapp-e0d07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrhzdroD1DdoLUdgk6WT85-MsE1yqyLa4',
    appId: '1:510267432954:ios:51b480ca3a4db643afce43',
    messagingSenderId: '510267432954',
    projectId: 'chatapp-e0d07',
    storageBucket: 'chatapp-e0d07.appspot.com',
    iosClientId: '510267432954-953g2c5e775ilfaao62kutp1meeqjsrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrhzdroD1DdoLUdgk6WT85-MsE1yqyLa4',
    appId: '1:510267432954:ios:51b480ca3a4db643afce43',
    messagingSenderId: '510267432954',
    projectId: 'chatapp-e0d07',
    storageBucket: 'chatapp-e0d07.appspot.com',
    iosClientId: '510267432954-953g2c5e775ilfaao62kutp1meeqjsrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
