// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjLuGvRewDcHaFH9x3_xMmU98wdK5JQpA',
    appId: '1:804203740100:web:9613217130e7aaf9938291',
    messagingSenderId: '804203740100',
    projectId: 'tastyapp-93ec3',
    authDomain: 'tastyapp-93ec3.firebaseapp.com',
    storageBucket: 'tastyapp-93ec3.appspot.com',
    measurementId: 'G-186LFB739K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD53CiVehfX4ifrZZgQlpdet1QFdBLrVIg',
    appId: '1:804203740100:android:44348ecb3578423e938291',
    messagingSenderId: '804203740100',
    projectId: 'tastyapp-93ec3',
    storageBucket: 'tastyapp-93ec3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjn41G_ZSwbvmaATdvTeD0xntpaReKgkM',
    appId: '1:804203740100:ios:f3e3c89c19e93d7c938291',
    messagingSenderId: '804203740100',
    projectId: 'tastyapp-93ec3',
    storageBucket: 'tastyapp-93ec3.appspot.com',
    iosClientId: '804203740100-gtba9k4asrud15p2mqdn7aft4ja3iaf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tastyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjn41G_ZSwbvmaATdvTeD0xntpaReKgkM',
    appId: '1:804203740100:ios:f3e3c89c19e93d7c938291',
    messagingSenderId: '804203740100',
    projectId: 'tastyapp-93ec3',
    storageBucket: 'tastyapp-93ec3.appspot.com',
    iosClientId: '804203740100-gtba9k4asrud15p2mqdn7aft4ja3iaf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tastyApp',
  );
}
